In [3]:
import pandas as pd

In [4]:
pwd

'/Users/shivamtyagi/Desktop/SJSU/1st Sem/CMPE-272/Project'

In [33]:
import pandas as pd
import pprint

traffic = pd.read_csv("Traffic_data.csv")

n = len(traffic)
print(n)
a=[]
b=[]
c=[]
final=[]
for i in range(0,n):
        final.append([0]);
        
for i in range(0,n):
        a.append(traffic.Site_No[i]);
        b.append(traffic.Connection[i]);
        c.append(traffic.Traffic[i]);
for i in range(n):
        final[i]= [a[i],b[i],c[i]];
# for i in range(n):
#         final[i]= [a[i],b[i],c[i]];
        
        
print(traffic.Traffic[1])
print("site--",a)
print("connected to--",b)
print("traffic--",c)
print("final--",final)
pp = pprint.PrettyPrinter(depth=6)
#pp.pprint(final)

48
234
site-- [1, 1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 15, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 29, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42]
connected to-- [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 14, 14, 0, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 28, 28, 0, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 42, 42, 0]
traffic-- [445, 234, 345, 234, 545, 123, 654, 324, 646, 234, 754, 145, 676, 788, 134, 0, 653, 234, 456, 154, 678, 798, 566, 789, 355, 784, 234, 457, 567, 255, 435, 0, 545, 345, 234, 647, 787, 453, 256, 586, 899, 567, 356, 255, 256, 789, 760, 0]
final-- [[1, 2, 445], [1, 3, 234], [1, 4, 345], [2, 5, 234], [3, 6, 545], [4, 7, 123], [5, 8, 654], [6, 9, 324], [7, 10, 646], [8, 11, 234], [9, 12, 754], [10, 13, 145], [11, 14, 676], [12, 14, 788], [13, 14, 134], [14, 0, 0], [15, 16, 653], [15, 17, 234], [15, 18, 456], [16, 19, 154], [17, 20, 678], [18, 21, 798], [19, 22, 566], [20, 23, 789], [21, 24, 355], [22, 25, 784], [23, 26, 234], [24, 27, 457], [25, 28, 567], [26, 28, 255], [27, 28, 435], [28, 0, 0], [29, 30, 545], [29, 31, 345], [29, 32, 234], [30, 33, 647], [31, 34, 787], [32, 35, 453], [33, 36, 256], [34, 37, 586], [35, 38, 899], [36, 39, 567], [37, 40, 356], [38, 41, 255], [39, 42, 256], [40, 42, 789], [41, 42, 760], [42, 0, 0]]

In [7]:
traffic

    Site_No        Date  Hour  Traffic  LeastTime  Connection
0         1  01/11/2018     7      445          3           2
1         1  01/11/2018     7      234          6           3
2         1  01/11/2018     7      345          5           4
3         2  01/11/2018     7      234          7           5
4         3  01/11/2018     7      545          9           6
5         4  01/11/2018     7      123          3           7
6         5  01/11/2018     7      654          6           8
7         6  01/11/2018     7      324          8           9
8         7  01/11/2018     7      646          3          10
9         8  01/11/2018     7      234          2          11
10        9  01/11/2018     7      754          6          12
11       10  01/11/2018     7      145          7          13
12       11  01/11/2018     7      676          5          14
13       12  01/11/2018     7      788          3          14
14       13  01/11/2018     7      134          7          14
15       14  01/11/2018     7        0          0           0
16       15  01/11/2018     7      653          4          16
17       15  01/11/2018     7      234          3          17
18       15  01/11/2018     7      456          6          18
19       16  01/11/2018     7      154          2          19
20       17  01/11/2018     7      678          7          20
21       18  01/11/2018     7      798          8          21
22       19  01/11/2018     7      566          4          22
23       20  01/11/2018     7      789          2          23
24       21  01/11/2018     7      355          7          24
25       22  01/11/2018     7      784          5          25
26       23  01/11/2018     7      234          4          26
27       24  01/11/2018     7      457          6          27
28       25  01/11/2018     7      567          4          28
29       26  01/11/2018     7      255          2          28
30       27  01/11/2018     7      435          7          28
31       28  01/11/2018     7        0          0           0
32       29  01/11/2018     7      545          3          30
33       29  01/11/2018     7      345          5          31
34       29  01/11/2018     7      234          2          32
35       30  01/11/2018     7      647          7          33
36       31  01/11/2018     7      787          7          34
37       32  01/11/2018     7      453          3          35
38       33  01/11/2018     7      256          2          36
39       34  01/11/2018     7      586          4          37
40       35  01/11/2018     7      899          5          38
41       36  01/11/2018     7      567          7          39
42       37  01/11/2018     7      356          7          40
43       38  01/11/2018     7      255          3          41
44       39  01/11/2018     7      256          3          42
45       40  01/11/2018     7      789          5          42
46       41  01/11/2018     7      760          6          42
47       42  01/11/2018     7        0          0           0